name: Deploy to Kubernetes

on:
  push:
    branches:
      - kube

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 'v1.33.1'
          driver: docker

      - name: Deploy to Kubernetes
        working-directory: ./frontend
        run: kubectl apply -f nginx-deployment.yaml

      - name: Verify Deployment
        run: kubectl get pods
