name: Test CI Workflow

on:
  push:
    branches:
      - Backend

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Install dependencies ..."
          node -v
          cd backend/
          npm install

      - name: Run tests
        run: |
          echo "Run tests ..."
          cd backend/
          npm test
          
      - name: Build application
        run: |
          echo "Build application ..."
          cd backend/
          npm run build
