name: Test CI Workflow

on:
  push:
    branches:
      - Backend

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Check Secret Presence and Length
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$MY_API_KEY" ]; then
            echo "Secret is empty or not set!"
            exit 1
          else
            echo "Secret is set."
            echo "Secret length: ${#MY_API_KEY}" # In ra độ dài của secret
          fi       


      
